import GifEncoder from './GifEncoder.js';

function captureEvent(type,detail){return new CustomEvent(`capture-${type}`,{detail});}
function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Unable to encode the captured image.')),type,quality));}
function supportedRecorderType(Recorder){for(const type of ['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4'])if(Recorder.isTypeSupported?.(type))return type;return '';}

export default class ScreenCapture extends EventTarget{
    constructor({mediaDevices=globalThis.navigator?.mediaDevices,Recorder=globalThis.MediaRecorder,documentRef=globalThis.document}={}){super();this.mediaDevices=mediaDevices;this.Recorder=Recorder;this.document=documentRef;this.mode='idle';this.stream=null;this.recorder=null;this.startedAt=0;this.frames=[];this.timer=0;this.video=null;this.canvas=null;this.stopPromise=null;}
    available(){return Boolean(this.mediaDevices?.getDisplayMedia&&this.document);}
    async acquire({audio=false}={}){if(!this.available())throw new Error('Display capture is unavailable in this browser.');return this.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:15,max:30}},audio:Boolean(audio)});}
    async captureImage({maxWidth=1920,type='image/png'}={}){this.assertIdle();this.emit('requesting',{mode:'image'});let stream;try{stream=await this.acquire();const {video,canvas}=await this.prepare(stream,maxWidth);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const blob=await canvasBlob(canvas,type);const result={blob,mimeType:type,extension:type==='image/jpeg'?'jpg':'png',duration:0,width:canvas.width,height:canvas.height};this.emit('result',result);return result}catch(error){this.emit('error',{error,mode:'image'});throw error}finally{this.stopTracks(stream)}}
    async startVideo({audio=true}={}){this.assertIdle();if(!this.Recorder)throw new Error('Video recording is unavailable in this browser.');this.emit('requesting',{mode:'video'});this.stream=await this.acquire({audio});const mimeType=supportedRecorderType(this.Recorder);const chunks=[];this.recorder=new this.Recorder(this.stream,mimeType?{mimeType}:undefined);this.stopPromise=new Promise((resolve,reject)=>{this.recorder.addEventListener('dataavailable',event=>{if(event.data?.size)chunks.push(event.data)});this.recorder.addEventListener('stop',()=>{const type=this.recorder.mimeType||mimeType||'video/webm';resolve({blob:new Blob(chunks,{type}),mimeType:type,extension:type.includes('mp4')?'mp4':'webm',duration:Date.now()-this.startedAt})},{once:true});this.recorder.addEventListener('error',event=>reject(event.error||new Error('Video recording failed.')),{once:true})});this.mode='video';this.startedAt=Date.now();this.recorder.start(500);this.emit('start',{mode:'video'});return true;}
    async startGif({maxWidth=640,frameDelay=250}={}){this.assertIdle();this.emit('requesting',{mode:'gif'});this.stream=await this.acquire();const prepared=await this.prepare(this.stream,maxWidth);this.video=prepared.video;this.canvas=prepared.canvas;this.frames=[];this.mode='gif';this.startedAt=Date.now();const context=this.canvas.getContext('2d',{willReadFrequently:true});const sample=()=>{context.drawImage(this.video,0,0,this.canvas.width,this.canvas.height);this.frames.push(context.getImageData(0,0,this.canvas.width,this.canvas.height))};sample();this.timer=setInterval(sample,Math.max(100,frameDelay));this.gifDelay=Math.max(100,frameDelay);this.emit('start',{mode:'gif'});return true;}
    async stop(){if(this.mode==='idle')return null;const mode=this.mode;try{let result;if(mode==='video'){this.recorder.stop();result=await this.stopPromise}else{clearInterval(this.timer);const encoder=new GifEncoder(this.canvas.width,this.canvas.height);for(const frame of this.frames)encoder.addFrame(frame,{delay:this.gifDelay});result={blob:encoder.encode(),mimeType:'image/gif',extension:'gif',duration:Date.now()-this.startedAt,width:this.canvas.width,height:this.canvas.height}}this.emit('result',result);return result}catch(error){this.emit('error',{error,mode});throw error}finally{this.stopTracks(this.stream);this.reset()}}
    assertIdle(){if(this.mode!=='idle')throw new Error('Stop the active capture before starting another one.');}
    async prepare(stream,maxWidth){const video=this.document.createElement('video');video.muted=true;video.playsInline=true;video.srcObject=stream;await new Promise((resolve,reject)=>{video.addEventListener('loadedmetadata',resolve,{once:true});video.addEventListener('error',()=>reject(new Error('Unable to read the selected display.')),{once:true})});await video.play();const scale=Math.min(1,Math.max(1,Number(maxWidth)||1920)/video.videoWidth);const canvas=this.document.createElement('canvas');canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));return {video,canvas};}
    stopTracks(stream){for(const track of stream?.getTracks?.()||[])track.stop()}
    reset(){clearInterval(this.timer);this.mode='idle';this.stream=null;this.recorder=null;this.frames=[];this.timer=0;this.video=null;this.canvas=null;this.stopPromise=null;this.startedAt=0;this.emit('stop',{});}
    emit(type,detail){this.dispatchEvent(captureEvent(type,detail));}
}
