import ApiModelDatabase from './ApiModelDatabase.js';
import {WeatherDay,WeatherLocation,WeatherObservation,WeatherSnapshot} from '../entities/Weather.js';

export const OPEN_METEO_ENDPOINTS=Object.freeze({geocoding:'https://geocoding-api.open-meteo.com/v1/search',forecast:'https://api.open-meteo.com/v1/forecast'});

export default class OpenMeteoWeatherProvider extends EventTarget{
    constructor({geocodingEndpoint=OPEN_METEO_ENDPOINTS.geocoding,forecastEndpoint=OPEN_METEO_ENDPOINTS.forecast,fetchImpl=globalThis.fetch}={}){super();this.geocoder=new ApiModelDatabase({endpoint:geocodingEndpoint,fetchImpl,parser:raw=>Array.from(raw.results||[],item=>new WeatherLocation({id:item.id,name:item.name,region:item.admin1||'',country:item.country||'',latitude:item.latitude,longitude:item.longitude,timezone:item.timezone||'auto'}))});this.forecast=new ApiModelDatabase({endpoint:forecastEndpoint,fetchImpl,parser:(raw,{context})=>mapForecast(raw,context.location)});for(const model of [this.geocoder,this.forecast]){model.addEventListener('api-model-request',event=>this.emit('request',event.detail));model.addEventListener('api-model-error',event=>this.emit('error',event.detail));}}
    setEndpoints({geocoding,forecast}={}){if(geocoding)this.geocoder.setEndpoint(geocoding);if(forecast)this.forecast.setEndpoint(forecast);return {geocoding:this.geocoder.endpoint,forecast:this.forecast.endpoint};}
    async search(query){const name=String(query||'').trim();if(name.length<2)throw new TypeError('Enter at least two characters for a location search.');const record=await this.geocoder.fetch({name,count:8,language:'en',format:'json'});this.emit('locations',{locations:record.value});return record.value;}
    async load(location,{temperatureUnit='fahrenheit',windSpeedUnit='mph',precipitationUnit='inch'}={}){const place=location instanceof WeatherLocation?location:new WeatherLocation(location);const record=await this.forecast.fetch({latitude:place.latitude,longitude:place.longitude,timezone:'auto',forecast_days:7,temperature_unit:temperatureUnit,wind_speed_unit:windSpeedUnit,precipitation_unit:precipitationUnit,current:['temperature_2m','relative_humidity_2m','apparent_temperature','precipitation','weather_code','wind_speed_10m','is_day'],daily:['weather_code','temperature_2m_max','temperature_2m_min','precipitation_probability_max','sunrise','sunset']},{location:place});this.emit('weather',{weather:record.value});return record.value;}
    emit(type,detail){this.dispatchEvent(new CustomEvent(`weather-${type}`,{detail}));}
}

export function mapForecast(raw,location){const current=raw.current||{},units=raw.current_units||{},daily=raw.daily||{},dailyUnits=raw.daily_units||{};const observation=new WeatherObservation({time:current.time,temperature:current.temperature_2m,apparentTemperature:current.apparent_temperature,humidity:current.relative_humidity_2m,precipitation:current.precipitation,weatherCode:current.weather_code,windSpeed:current.wind_speed_10m,isDay:current.is_day===1,temperatureUnit:units.temperature_2m||'°',windUnit:units.wind_speed_10m||''});const days=Array.from(daily.time||[],(date,index)=>new WeatherDay({date,weatherCode:daily.weather_code?.[index],temperatureMax:daily.temperature_2m_max?.[index],temperatureMin:daily.temperature_2m_min?.[index],precipitationProbability:daily.precipitation_probability_max?.[index]??0,sunrise:daily.sunrise?.[index]||'',sunset:daily.sunset?.[index]||'',temperatureUnit:dailyUnits.temperature_2m_max||units.temperature_2m||'°'}));return new WeatherSnapshot({location,current:observation,daily:days,source:'Open-Meteo',fetchedAt:new Date()});}
